targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "warn"
unsound = "deny"
yanked = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
copyleft = "deny"
default = "warn"
unused-allowed-license = "deny"
confidence-threshold = 0.95
allow = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "simplest-path"
skip-tree = []
